In [8]:
# 1. Get the data ready
# 2. Pick a model/estimator (to suit your problem)
# 3. Fit the model to the data and make a prediction
# 4. Evaluate the model
# 5. Improve through experimentation
# 6. Save and reload your trained model
# 7. Putting it all together (not pictured)

In [10]:
# 1.get the data ready
import pandas as pd
heart_disease = pd.read_csv("C:/Users/RAJA KANNAN/Desktop/udemy machine learning/data/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [11]:
#Create X (features matrix)
X = heart_disease.drop("target", axis=1)

#Create Y (Labels)
y = heart_disease['target']

In [12]:
#2.Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

# We will keep the hyper parameters
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [14]:
model.fit(X_train, y_train);

In [15]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
163   38    1   2       138   175    0        1      173      0      0.0   
78    52    1   1       128   205    1        1      184      0      0.0   
288   57    1   0       110   335    0        1      143      1      3.0   
57    45    1   0       115   260    0        0      185      0      0.0   
282   59    1   2       126   218    1        1      134      0      2.2   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
11    48    0   2       130   275    0        1      139      0      0.2   
114   55    1   1       130   262    0        1      155      0      0.0   
230   47    1   2       108   243    0        1      152      0      0.0   
293   67    1   2       152   212    0        0      150      0      0.8   
215   43    0   0       132   341    1        0      136      1      3.0   

     slope  ca  thal  
163      2   4     2  
78       2   0     2  
288      1   1     3  
57       2   0     2  
282      1   1     1  
..     ...  ..   ...  
11       2   0     2  
114      2   0     2  
230      2   0     2  
293      1   0     3  
215      1   0     3  

[61 rows x 13 columns]

In [16]:
y_test

163    1
78     1
288    0
57     1
282    0
      ..
11     1
114    1
230    0
293    0
215    0
Name: target, Length: 61, dtype: int64

In [17]:
# Make a prediction
y_preds = model.predict(X_test)
y_preds

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [18]:
# 4.Evaluate the model on the training data and test data
model.score(X_train, y_train)

1.0

In [19]:
model.score(X_test, y_test)

0.7540983606557377

In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.70      0.73      0.72        26
           1       0.79      0.77      0.78        35

    accuracy                           0.75        61
   macro avg       0.75      0.75      0.75        61
weighted avg       0.76      0.75      0.75        61



In [21]:
confusion_matrix(y_test, y_preds)

array([[19,  7],
       [ 8, 27]], dtype=int64)

In [22]:
accuracy_score(y_test, y_preds)

0.7540983606557377

In [24]:
import numpy as np

In [25]:
# 5.Improve a model
# Try different amount of n_estimators
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators..")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy of test set: {model.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 10 estimators..
Model accuracy of test set: 78.69%

Trying model with 20 estimators..
Model accuracy of test set: 81.97%

Trying model with 30 estimators..
Model accuracy of test set: 77.05%

Trying model with 40 estimators..
Model accuracy of test set: 78.69%

Trying model with 50 estimators..
Model accuracy of test set: 78.69%

Trying model with 60 estimators..
Model accuracy of test set: 73.77%

Trying model with 70 estimators..
Model accuracy of test set: 78.69%

Trying model with 80 estimators..
Model accuracy of test set: 80.33%

Trying model with 90 estimators..
Model accuracy of test set: 80.33%



In [26]:
#6. Save model and load it
import pickle

pickle.dump(model, open("random_forest_model.pkl", "wb"))  #wb=write binary

# 1.1 Make sure its all numerical

In [27]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [28]:
car_sales = pd.read_csv("C:/Users/RAJA KANNAN/Desktop/udemy machine learning/data/car-sales.csv")
car_sales

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [29]:
car_sales["Price"] = car_sales["Price"].str.replace('[$/,/.]', '', regex=True)
car_sales

Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White         150043      4   400000
1   Honda    Red          87899      4   500000
2  Toyota   Blue          32549      3   700000
3     BMW  Black          11179      5  2200000
4  Nissan  White         213095      4   350000
5  Toyota  Green          99213      4   450000
6   Honda   Blue          45698      4   750000
7   Honda   Blue          54738      4   700000
8  Toyota  White          60000      4   625000
9  Nissan  White          31600      4   970000

In [30]:
len(car_sales)

10

In [31]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [34]:
#split into x and y
X = car_sales.drop("Price", axis=1)
y = car_sales['Price']

#Split into train and test
X_train, X_text, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [33]:
#Build Machine learning Model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Honda'

In [40]:
#turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                                 remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 1.50043e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 8.78990e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 3.25490e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 1.00000e+00, 1.11790e+04],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 2.13095e+05],
       [0.00000e+00, 0.00000e+

In [41]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  150043.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   87899.0
2  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   32549.0
3  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   11179.0
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  213095.0
5  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0   99213.0
6  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   45698.0
7  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   54738.0
8  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   60000.0
9  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   31600.0

In [42]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0      4     False       False        False         True         False   
1      4     False        True        False        False         False   
2      3     False       False        False         True         False   
3      5      True       False        False        False          True   
4      4     False       False         True        False         False   
5      4     False       False        False         True         False   
6      4     False        True        False        False         False   
7      4     False        True        False        False         False   
8      4     False       False        False         True         False   
9      4     False       False         True        False         False   

   Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0        False         False       False          True  
1        False         False        True         False  
2         True         False       False         False  
3        False         False       False         False  
4        False         False       False          True  
5        False          True       False         False  
6         True         False       False         False  
7         True         False       False         False  
8        False         False       False          True  
9        False         False       False          True

In [43]:
#Lets refit the model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, 
                                                    y,
                                                   test_size=0.2)
model.fit(X_train, y_train)

RandomForestRegressor()

# What if there were missing values?
1.Fill them with some value(also known as inputation)

2.Remove the samples with missing data altogether.

In [49]:
# Import car sales missing data
car_sales_missing = pd.read_csv("C:/Users/RAJA KANNAN/Desktop/udemy machine learning/data/car-sales-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500

In [51]:
car_sales_missing['Price'] = car_sales_missing['Price'].str.replace('[$/,/.]', '', regex=True)
car_sales_missing

Make Colour  Odometer  Doors  Price
0  Toyota  White  150043.0    4.0   4000
1   Honda    Red   87899.0    4.0   5000
2  Toyota   Blue       NaN    3.0   7000
3     BMW  Black   11179.0    5.0  22000
4  Nissan  White  213095.0    4.0   3500
5  Toyota  Green       NaN    4.0   4500
6   Honda    NaN       NaN    4.0   7500
7   Honda   Blue       NaN    4.0    NaN
8  Toyota  White   60000.0    NaN    NaN
9     NaN  White   31600.0    4.0   9700

In [52]:
car_sales_missing.isna().sum()

Make        1
Colour      1
Odometer    4
Doors       1
Price       2
dtype: int64

In [54]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [59]:
# lets try and convert into numbers
#turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                                 remainder="passthrough")
transformed_X = transformer.fit_transform(X);
transformed_X

<10x16 sparse matrix of type '<class 'numpy.float64'>'
	with 40 stored elements in Compressed Sparse Row format>

In [61]:
car_sales_missing["Doors"].value_counts()

Doors
4.0    7
3.0    1
5.0    1
Name: count, dtype: int64

# OPTION 1 : Fill missing data with pandas


In [74]:
#Fill the make column
car_sales_missing["Make"].fillna("missing", inplace=True)

#Fill the colour column
car_sales_missing["Colour"].fillna("missing", inplace=True)

#Fill the odometer column
car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(), inplace=True)

#Fill the door column
car_sales_missing["Doors"].fillna(4, inplace=True)

In [75]:
car_sales_missing.isna().sum()

Make        0
Colour      0
Odometer    0
Doors       0
Price       2
dtype: int64

In [72]:
print(car_sales_missing.columns)

Index(['Make', 'Colour', 'Odometer', 'Doors', 'Price'], dtype='object')


In [77]:
#Remove rows with missing price value
car_sales_missing.dropna(inplace=True)

In [78]:
car_sales_missing.isna().sum()

Make        0
Colour      0
Odometer    0
Doors       0
Price       0
dtype: int64

In [79]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [81]:
# lets try and convert into numbers
#turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                                 remainder="passthrough")
transformed_X = transformer.fit_transform(car_sales_missing);
transformed_X

array([[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 150043.0, '4000'],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 87899.0, '5000'],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 92302.66666666667, '7000'],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 11179.0, '22000'],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 213095.0, '3500'],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 92302.66666666667, '4500'],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 92302.66666666667, '7500'],
       [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 31600.0, '9700']], dtype=object)

In [ ]:
OPTION 1 : Fill missing data with pandas

In [82]:
import sklearn
sklearn.__version__

'1.3.0'